apiVersion: v1
kind: Service
metadata:
    name: kubedoom
    namespace: '{{.Release.Namespace}}'
spec:
    type: ClusterIP
    ports:
      - protocol: TCP
        name: novnc
        port: 5900
    selector:
        app: kubedoom
---
apiVersion: v1
kind: Service
metadata:
    name: novnc
    namespace: '{{.Release.Namespace}}'
spec:
    type: LoadBalancer
    ports:
      - protocol: TCP
        name: novnc
        port: 6080
    selector:
        app: novnc
