apiVersion: v1
kind: Service
metadata:
    name: {{ include "helm-chart.fullname" . }}-kubedoom
    namespace: '{{.Release.Namespace}}'
spec:
    type: ClusterIP
    ports:
      - protocol: TCP
        name: novnc
        port: 5900
    selector:
        app: kubedoom
---
apiVersion: v1
kind: Service
metadata:
    name: {{ include "helm-chart.fullname" . }}-novnc
    namespace: '{{.Release.Namespace}}'
spec:
  type: {{ .Values.service.type | default "LoadBalancer" }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end -}}
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- range .Values.service.loadBalancerSourceRanges }}
    - {{ . }}
  {{- end }}
  {{- end }}
  {{- end }} # END loadbalancer
  {{- if and .Values.service.clusterIP (eq .Values.service.type "ClusterIP") }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  {{- if .Values.service.externalIPs }}
  externalIPs:
    {{- toYaml .Values.service.externalIPs | nindent 4 }}
  {{- end }}
  {{- if .Values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ .Values.service.ipFamilyPolicy }}
  {{- end }}
  {{- with .Values.service.ipFamilies }}
  ipFamilies:
  {{- toYaml . | nindent 4 }}
  {{- end -}}
  {{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  ports:
  - protocol: TCP
    name: novnc
    port: {{ .Values.service.targetPort | default "6080" }}
    {{- if .Values.service.nodePort }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
  selector:
    app: novnc
