# Settings for the chart.

# nameOverride Replaces the release name of the chart in Chart.yaml file when
# this is used to construct Kubernetes object names
nameOverride: ""
# fullnameOverride completely replaces the generated release name
fullnameOverride: ""

kubedoom_namespace: ""

service:
  type: ""
  port: ""
  externalIPs: {}
  ipFamilyPolicy: ""
  ipFamilies: {}
  externalTrafficPolicy: ""
  targetPort: ""
  nodePort: ""